name: ebuzz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  autocomplete_textfield: ^1.7.3
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  flutter_barcode_scanner: ^1.0.1
  flutter_spinkit: ^4.1.2+1
  flutter_typeahead: ^1.8.8
  fluttertoast: ^7.1.1
  get: ^3.15.0
  http: ^0.12.2
  shared_preferences: ^0.5.10
  intl: ^0.16.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test:
  flutter_launcher_icons: '^0.8.0'
  integration_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
