name: ebuzz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.1
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_local_notifications: ^5.0.0+4
  flutter_riverpod: ^0.13.1
  flutter_secure_storage: ^4.2.0
  flutter_slidable: ^0.6.0
  flutter_typeahead: ^3.1.3
  fluttertoast: ^8.0.7
  get: ^4.1.4
  http: ^0.13.3
  image_picker: ^0.7.5
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  uuid: ^3.0.4
  flutter_uploader: ^1.2.1
  flutter_email_sender: ^5.0.0
  permission_handler: ^8.0.0+2
  file_utils: ^1.0.0
  downloads_path_provider: ^0.1.0
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: '^0.9.0'
  test: null
  build_runner: ^1.12.2
  build_web_compilers: ^2.16.5

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
