name: ebuzz
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  autocomplete_textfield: ^1.7.3
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  flutter_barcode_scanner: ^1.0.1
  flutter_spinkit: ^4.1.2+1
  flutter_typeahead: ^1.8.8
  fluttertoast: ^7.1.1
  get: ^3.15.0
  http: ^0.12.2
  image_picker: ^0.6.7
  image_pickers: ^1.0.8+7
  intl: ^0.16.1
  path: ^1.8.0
  path_provider: ^1.6.11
  shared_preferences: ^0.5.10
  thumbnails: ^1.0.1
  flutter_riverpod: ^0.13.1
  badges: any
  flutter_elegant_number_button: any
  flutter_secure_storage: any
  flutter_slidable: any

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: '^0.8.0'
  test: null

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
