class DoctypeNames {
  static const String batch = 'Batch';
  static const String bom = 'BOM';
  static const String brand = 'Brand';
  static const String company = 'Company';
  static const String currency = 'Currency';
  static const String customer = 'Customer';
  static const String customerGroup = 'Customer Group';
  static const String deliveryNote = 'Delivery Note';
  static const String evaluasiStaff = 'Evaluasi Staff'; //
  static const String globalDefaults = 'Global Defaults'; //
  static const String item = 'Item';
  static const String itemGroup = 'Item Group';
  static const String lead = 'Lead';
  static const String leaveApplication = 'Leave Application';
  static const String leaveLedgerEntry = 'Leave Ledger Entry'; //
  static const String location = 'Location';
  static const String purchaseInvoice = 'Purchase Invoice';
  static const String purchaseOrder = 'Purchase Order';
  static const String purchaseReceipt = 'Purchase Receipt';
  static const String qualityInspection = 'Quality Inspection'; 
  static const String qualityInspectionTemplate = 'Quality Inspection Template';
  static const String quotation = 'Quotation';
  static const String salesInvoice = 'Sales Invoice';
  static const String salesOrder = 'Sales Order';
  static const String stockEntry = 'Stock Entry';
  static const String stockLedger = 'Stock Ledger';
  static const String stockLedgerEntry = 'Stock Ledger Entry';
  static const String territory = 'Territory';
  static const String uom = 'Unit of Measure (UOM)'; // Unit of Measure (UOM)
  static const String user = 'User';
  static const String warehouse = 'Warehouse';
  static const String workOrder = 'Work Order';
}
